import fs from 'node:fs';
import path from 'node:path';

const outDir = path.resolve('public/downloads');
const md = text => ({ cell_type: 'markdown', metadata: {}, source: text.split('\n').map((line, i, a) => line + (i < a.length - 1 ? '\n' : '')) });
const code = text => ({ cell_type: 'code', execution_count: null, metadata: {}, outputs: [], source: text.split('\n').map((line, i, a) => line + (i < a.length - 1 ? '\n' : '')) });
const notebook = cells => ({
  cells,
  metadata: {
    kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
    language_info: { name: 'python', version: '3' },
    colab: { name: 'SDA-AIE-111', provenance: [] }
  },
  nbformat: 4,
  nbformat_minor: 5
});
const save = (name, cells) => fs.writeFileSync(path.join(outDir, name), JSON.stringify(notebook(cells), null, 2) + '\n');

const DATA = "DATA_URL = 'https://raw.githubusercontent.com/hanenalmayouf/FAML/main/public/data/manafeth_customers.csv'";

save('SDA-AIE-111_Day1_Interactive_Workbook.ipynb', [
  md('# تطبيق اليوم الأول — شاهد أنواع تعلم الآلة على بيانات منافذ\nهذا تطبيق مشاهدة موجّه للمبتدئ. شغّل خلية واحدة في كل مرة، ثم اقرأ التفسير الذي يليها. جميع الأكواد مكتملة.'),
  md('## 1) تحميل البيانات\n### الخطوة 1: استيراد pandas\nنستورد مكتبة **pandas** لقراءة الجدول والتعامل معه.'),
  code('import pandas as pd'),
  md('### الخطوة 2: تحديد رابط الملف\nنحفظ مكان ملف البيانات في متغير اسمه `DATA_URL`.'),
  code(DATA),
  md('### الخطوة 3: قراءة الملف\n`read_csv` تقرأ الملف وتضعه في جدول اسمه `df`.'),
  code("df = pd.read_csv(DATA_URL)\nprint('تم تحميل البيانات ✅')"),
  md('### الخطوة 4: معرفة حجم الجدول\n`shape` تعرض عدد الصفوف أولًا ثم عدد الأعمدة.'),
  code("print('حجم الجدول:', df.shape)"),
  md('**اقرأ الناتج:** `(48000, 19)` يعني 48,000 صف و19 عمودًا.'),
  md('### الخطوة 5: مشاهدة أول خمس حالات\n`head()` تساعدنا على فهم شكل الصفوف والأعمدة.'),
  code('display(df.head())'),

  md('## 2) مثال تصنيف (Classification)\nالسؤال: هل سيتوقف العميل أم لا؟ المخرج فئة: `0` أو `1`.'),
  md('### الخطوة 1: اختيار الخصائص X\nنختار أربعة أعمدة رقمية بسيطة يستخدمها النموذج.'),
  code("classification_features = [\n    'orders_per_month',\n    'avg_basket_sar',\n    'days_since_last_order',\n    'promo_usage_rate'\n]\nX_class = df[classification_features]"),
  md('### الخطوة 2: اختيار الإجابة y\nالعمود `churned_30d` هو الإجابة التي نريد من النموذج تعلمها.'),
  code("y_class = df['churned_30d']\nprint(y_class.value_counts())"),
  md('**اقرأ الناتج:** نرى عدد حالات الفئة 0 وعدد حالات الفئة 1.'),
  md('### الخطوة 3: تقسيم البيانات\nنعطي النموذج جزءًا للتعلم ونحتفظ بجزء للاختبار.'),
  code("from sklearn.model_selection import train_test_split\n\nXc_train, Xc_test, yc_train, yc_test = train_test_split(\n    X_class, y_class, test_size=0.20, stratify=y_class, random_state=42\n)"),
  md('### الخطوة 4: إنشاء نموذج التصنيف\nنستخدم شجرة قرار صغيرة حتى تكون الفكرة واضحة.'),
  code("from sklearn.tree import DecisionTreeClassifier\n\nclassifier = DecisionTreeClassifier(max_depth=3, random_state=42)"),
  md('### الخطوة 5: تدريب النموذج\n`fit` تجعل النموذج يتعلم العلاقة بين X وy من بيانات التدريب.'),
  code('classifier.fit(Xc_train, yc_train)'),
  md('### الخطوة 6: إنتاج التوقعات\n`predict` تطلب من النموذج اختيار الفئة لكل حالة في الاختبار.'),
  code('class_prediction = classifier.predict(Xc_test)'),
  md('### الخطوة 7: مقارنة التوقع بالحقيقة'),
  code("classification_result = pd.DataFrame({\n    'الحقيقة': yc_test.iloc[:10].values,\n    'توقع النموذج': class_prediction[:10]\n})\ndisplay(classification_result)"),
  md('**اقرأ الناتج:** التطابق يعني توقعًا صحيحًا. الاختلاف يعني أن النموذج أخطأ في تلك الحالة.'),

  md('## 3) مثال انحدار (Regression)\nالسؤال: كم ستكون قيمة سلة العميل؟ المخرج رقم بالريال.'),
  md('### الخطوة 1: اختيار X وy للانحدار'),
  code("regression_features = [\n    'orders_per_month',\n    'days_since_last_order',\n    'promo_usage_rate',\n    'tenure_months'\n]\nX_reg = df[regression_features]\ny_reg = df['avg_basket_sar']"),
  md('### الخطوة 2: تقسيم بيانات الانحدار'),
  code("Xr_train, Xr_test, yr_train, yr_test = train_test_split(\n    X_reg, y_reg, test_size=0.20, random_state=42\n)"),
  md('### الخطوة 3: إنشاء نموذج الانحدار الخطي'),
  code('from sklearn.linear_model import LinearRegression\n\nregressor = LinearRegression()'),
  md('### الخطوة 4: تدريب نموذج الانحدار'),
  code('regressor.fit(Xr_train, yr_train)'),
  md('### الخطوة 5: توقع أرقام جديدة'),
  code('number_prediction = regressor.predict(Xr_test)'),
  md('### الخطوة 6: عرض الحقيقة والتوقع'),
  code("regression_result = pd.DataFrame({\n    'الحقيقة بالريال': yr_test.iloc[:10].round(2).values,\n    'توقع النموذج': number_prediction[:10].round(2)\n})\ndisplay(regression_result)"),
  md('**اقرأ الناتج:** الفرق بين الرقم الحقيقي والمتوقع هو خطأ النموذج في تلك الحالة.'),

  md('## 4) مثال تعلم غير خاضع للإشراف — K-Means\nلا يوجد هدف y. نطلب من الخوارزمية جمع العملاء المتشابهين.'),
  md('### الخطوة 1: اختيار خصائص التجميع'),
  code("cluster_features = [\n    'orders_per_month',\n    'avg_basket_sar',\n    'days_since_last_order',\n    'promo_usage_rate'\n]\nX_cluster = df[cluster_features]"),
  md('### الخطوة 2: توحيد مقياس الأرقام\n`StandardScaler` يمنع العمود ذي الأرقام الكبيرة من السيطرة على المسافة.'),
  code('from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\nX_cluster_scaled = scaler.fit_transform(X_cluster)'),
  md('### الخطوة 3: إنشاء K-Means بثلاث مجموعات'),
  code('from sklearn.cluster import KMeans\n\nkmeans = KMeans(n_clusters=3, n_init=10, random_state=42)'),
  md('### الخطوة 4: اكتشاف مجموعة كل عميل'),
  code('cluster_number = kmeans.fit_predict(X_cluster_scaled)'),
  md('### الخطوة 5: إضافة رقم المجموعة إلى نسخة من الجدول'),
  code("df_clusters = df.copy()\ndf_clusters['cluster'] = cluster_number"),
  md('### الخطوة 6: فهم متوسط خصائص كل مجموعة'),
  code("cluster_profile = (\n    df_clusters.groupby('cluster')[cluster_features]\n    .mean()\n    .round(2)\n)\ndisplay(cluster_profile)"),
  md('**اقرأ الناتج:** رقم المجموعة لا يحمل معنى جاهزًا. نفسّر المجموعة من متوسط خصائصها ثم نعطيها اسمًا وصفيًا.'),
  md('## الخلاصة\n- التصنيف أعطى فئة.\n- الانحدار أعطى رقمًا.\n- K-Means اكتشفت مجموعات من دون y.\n\nلم نطلب منك كتابة كود؛ الهدف أن ترى رحلة كل نوع خطوة بخطوة.')
]);

save('SDA-AIE-111_Day2_Full_Day_Lab.ipynb', [
  md('# اليوم الثاني — من البيانات الخام إلى أول نموذج\nكل خلية تنفذ فكرة واحدة. شغّلها ثم اقرأ الناتج قبل الانتقال.'),
  md('## المحطة 0 — تحميل بيانات منافذ'),
  md('### 0.1 استيراد pandas'), code('import pandas as pd'),
  md('### 0.2 تحديد رابط الملف'), code(DATA),
  md('### 0.3 قراءة الملف'), code("df = pd.read_csv(DATA_URL)\nprint('تم التحميل ✅')"),

  md('# المحطة 1 — افهم الجدول'),
  md('### 1.1 حجم الجدول'), code("print('عدد الصفوف والأعمدة:', df.shape)"),
  md('### 1.2 أول خمس حالات'), code('display(df.head())'),
  md('### 1.3 أسماء الأعمدة'), code('print(df.columns.tolist())'),
  md('### 1.4 أنواع الأعمدة'), code('display(df.dtypes.to_frame(name="نوع البيانات"))'),
  md('**ماذا تعلمنا؟** عرفنا حجم الجدول وأسماء الأعمدة وأنواعها قبل اتخاذ أي قرار تنظيف.'),

  md('# المحطة 2 — افحص الجودة ونظّف نسخة من البيانات'),
  md('### 2.1 حساب القيم المفقودة'),
  code("missing_count = df.isna().sum()\ndisplay(missing_count[missing_count > 0].to_frame('عدد المفقود'))"),
  md('### 2.2 حساب نسبة القيم المفقودة'),
  code("missing_percent = df.isna().mean().mul(100).round(1)\ndisplay(missing_percent[missing_percent > 0].to_frame('نسبة المفقود %'))"),
  md('### 2.3 إنشاء نسخة للتنظيف\nنحافظ على `df` كما هو، ونجري التعديلات على `clean_df`.'),
  code('clean_df = df.copy()'),
  md('### 2.4 إنشاء مؤشر لغياب التقييم\nالقيمة 1 تعني أن التقييم كان مفقودًا.'),
  code("clean_df['rating_missing'] = clean_df['avg_rating'].isna().astype(int)\ndisplay(clean_df[['avg_rating', 'rating_missing']].head())"),
  md('### 2.5 تعويض التقييم بالوسيط'),
  code("rating_median = clean_df['avg_rating'].median()\nclean_df['avg_rating'] = clean_df['avg_rating'].fillna(rating_median)\nprint('الوسيط المستخدم:', rating_median)"),
  md('### 2.6 تعويض العرض المفقود بفئة واضحة'),
  code("clean_df['last_promo_used'] = clean_df['last_promo_used'].fillna('never_used')"),
  md('### 2.7 فحص الصفوف المكررة'),
  code("duplicate_rows = clean_df.duplicated().sum()\nprint('عدد الصفوف المكررة:', duplicate_rows)"),
  md('### 2.8 فحص نطاق التقييم'),
  code("invalid_rating = ~clean_df['avg_rating'].between(1, 5)\nprint('عدد التقييمات خارج 1 إلى 5:', invalid_rating.sum())"),
  md('### 2.9 مشاهدة أعلى قيم السلة قبل اتخاذ القرار'),
  code("display(clean_df.nlargest(10, 'avg_basket_sar')[['customer_id', 'avg_basket_sar']])"),
  md('**القرار المحلول:** نبقي القيمة المرتفعة؛ لأنها ممكنة وليست دليلًا كافيًا على خطأ إدخال.'),

  md('# المحطة 3 — جهّز X وy ومنع التسريب'),
  md('### 3.1 حفظ الهدف y أولًا'), code("y = clean_df['churned_30d'].copy()"),
  md('### 3.2 تحديد الأعمدة التي لا تدخل في X'),
  code("drop_cols = [\n    'customer_id', 'churned_30d',\n    'refund_issued', 'support_ticket_after_snapshot', 'next_month_orders',\n    'signup_date', 'snapshot_date'\n]"),
  md('### 3.3 إنشاء X'), code('X = clean_df.drop(columns=drop_cols, errors="ignore")'),
  md('### 3.4 التأكد من الحجم'), code("print('X:', X.shape)\nprint('y:', y.shape)"),

  md('# المحطة 4 — تقسيم البيانات وبناء Pipeline'),
  md('### 4.1 تقسيم البيانات'),
  code("from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.20, stratify=y, random_state=42\n)"),
  md('### 4.2 معرفة الأعمدة الرقمية'), code("numeric_cols = X.select_dtypes(include='number').columns.tolist()\nprint(numeric_cols)"),
  md('### 4.3 معرفة الأعمدة الفئوية'), code("categorical_cols = X.select_dtypes(exclude='number').columns.tolist()\nprint(categorical_cols)"),
  md('### 4.4 مسار تجهيز الأرقام'),
  code("from sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler\n\nnumeric_pipe = Pipeline([\n    ('impute', SimpleImputer(strategy='median')),\n    ('scale', StandardScaler())\n])"),
  md('### 4.5 مسار تجهيز الفئات'),
  code("from sklearn.preprocessing import OneHotEncoder\n\ncategorical_pipe = Pipeline([\n    ('impute', SimpleImputer(strategy='most_frequent')),\n    ('encode', OneHotEncoder(handle_unknown='ignore'))\n])"),
  md('### 4.6 جمع المسارين'),
  code("from sklearn.compose import ColumnTransformer\n\npreprocess = ColumnTransformer([\n    ('numbers', numeric_pipe, numeric_cols),\n    ('categories', categorical_pipe, categorical_cols)\n])"),

  md('# المحطة 5 — Baseline ثم نموذج تصنيف'),
  md('### 5.1 إنشاء خط الأساس (Baseline)'),
  code("from sklearn.dummy import DummyClassifier\n\nbaseline = Pipeline([\n    ('preprocess', preprocess),\n    ('model', DummyClassifier(strategy='most_frequent'))\n])"),
  md('### 5.2 تدريب خط الأساس'), code('baseline.fit(X_train, y_train)'),
  md('### 5.3 قياس Accuracy لخط الأساس'), code("baseline_accuracy = baseline.score(X_test, y_test)\nprint('Baseline Accuracy:', round(baseline_accuracy, 3))"),
  md('### 5.4 إنشاء Logistic Regression'),
  code("from sklearn.linear_model import LogisticRegression\n\nlogistic_model = Pipeline([\n    ('preprocess', preprocess),\n    ('model', LogisticRegression(max_iter=1000))\n])"),
  md('### 5.5 تدريب النموذج'), code('logistic_model.fit(X_train, y_train)'),
  md('### 5.6 إنتاج الفئات المتوقعة'), code('test_prediction = logistic_model.predict(X_test)'),
  md('### 5.7 إنتاج احتمال الفئة 1'), code('test_probability = logistic_model.predict_proba(X_test)[:, 1]'),
  md('### 5.8 مشاهدة أول عشر نتائج'),
  code("result = pd.DataFrame({\n    'الحقيقة': y_test.iloc[:10].values,\n    'التوقع': test_prediction[:10],\n    'احتمال التوقف': test_probability[:10].round(3)\n})\ndisplay(result)"),
  md('## الخلاصة\nمررنا بالترتيب: فهم الجدول ← فحص الجودة ← التنظيف ← تحديد X وy ← التقسيم ← تجهيز البيانات ← Baseline ← أول نموذج.')
]);

save('SDA-AIE-111_Day2_KMeans.ipynb', [
  md('# تطبيق K-Means لليوم الثاني — التعلم غير الخاضع للإشراف\nكل خلية تجيب عن سؤال واحد. لا توجد أكواد ناقصة.'),
  md('## 0) تحميل البيانات'),
  md('### 0.1 استيراد pandas'), code('import pandas as pd'),
  md('### 0.2 قراءة الملف'), code(`${DATA}\ndf = pd.read_csv(DATA_URL)\nprint('تم التحميل ✅', df.shape)`),
  md('## 1) اختيار الخصائص'),
  md('### 1.1 تحديد أسماء الخصائص السلوكية'),
  code("features = [\n    'orders_per_month',\n    'avg_basket_sar',\n    'days_since_last_order',\n    'promo_usage_rate'\n]"),
  md('### 1.2 إنشاء X من دون هدف y'), code('X_cluster = df[features].copy()'),
  md('### 1.3 مشاهدة ملخص الخصائص'), code('display(X_cluster.describe().round(2))'),
  md('## 2) تجهيز الأرقام'),
  md('### 2.1 تعويض المفقود بالوسيط'),
  code("from sklearn.impute import SimpleImputer\n\nimputer = SimpleImputer(strategy='median')\nX_filled = imputer.fit_transform(X_cluster)"),
  md('### 2.2 تطبيق التحجيم (Scaling)'),
  code("from sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X_filled)"),
  md('**لماذا؟** K-Means تعتمد على المسافة، لذلك نوحّد المقاييس قبل التجميع.'),
  md('## 3) مقارنة قيم K'),
  md('### 3.1 استيراد الأدوات'), code('from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score'),
  md('### 3.2 تجربة K من 2 إلى 6\nهذه الخلية تكرر **الفكرة نفسها** لخمس قيم، لذلك وجود الحلقة هنا مقصود.'),
  code("k_results = []\nfor k in range(2, 7):\n    candidate = KMeans(n_clusters=k, n_init=10, random_state=42)\n    labels = candidate.fit_predict(X_scaled)\n    k_results.append({\n        'K': k,\n        'Silhouette': silhouette_score(X_scaled, labels)\n    })"),
  md('### 3.3 عرض جدول المقارنة'), code('k_table = pd.DataFrame(k_results)\ndisplay(k_table.round(3))'),
  md('## 4) بناء المثال النهائي باستخدام K = 3'),
  md('### 4.1 إنشاء النموذج'), code('kmeans = KMeans(n_clusters=3, n_init=10, random_state=42)'),
  md('### 4.2 اكتشاف المجموعات'), code('cluster_labels = kmeans.fit_predict(X_scaled)'),
  md('### 4.3 إضافة رقم المجموعة'), code("clustered_df = df.copy()\nclustered_df['cluster'] = cluster_labels"),
  md('### 4.4 حساب متوسط كل خاصية داخل كل مجموعة'),
  code("cluster_profile = (\n    clustered_df.groupby('cluster')[features]\n    .mean()\n    .round(2)\n)\ndisplay(cluster_profile)"),
  md('### 4.5 معرفة الخاصية الأكثر اختلافًا بين المجموعات'),
  code("feature_range = cluster_profile.max() - cluster_profile.min()\nstrongest_feature = feature_range.idxmax()\nprint('أوضح خاصية تفصل المجموعات:', strongest_feature)"),
  md('## الخلاصة\nاخترنا الخصائص، عوضنا المفقود، طبقنا Scaling، قارنا قيم K، ثم فسرنا المجموعات من متوسطاتها.')
]);

save('SDA-AIE-111_Day3_Model_Selection.ipynb', [
  md('# اليوم الثالث — التعلم الخاضع للإشراف\nنبدأ بنموذج التصنيف الذي بُني في اليوم الثاني، ثم نقرأ العتبة، ونبني الانحدار، ونقارن نموذجين.'),
  md('## المحطة 0 — تحميل البيانات'),
  md('### 0.1 استيراد المكتبات الأساسية'), code('import numpy as np\nimport pandas as pd'),
  md('### 0.2 قراءة الملف'), code(`${DATA}\ndf = pd.read_csv(DATA_URL)\nprint('تم التحميل ✅', df.shape)`),

  md('# المحطة 1 — بناء مسار التصنيف'),
  md('### 1.1 تحديد الهدف'), code("y = df['churned_30d'].copy()"),
  md('### 1.2 تحديد الأعمدة المستبعدة'),
  code("drop_cols = [\n    'customer_id', 'churned_30d',\n    'refund_issued', 'support_ticket_after_snapshot', 'next_month_orders',\n    'signup_date', 'snapshot_date'\n]"),
  md('### 1.3 إنشاء X'), code('X = df.drop(columns=drop_cols, errors="ignore")'),
  md('### 1.4 فصل الاختبار النهائي'),
  code("from sklearn.model_selection import train_test_split\n\nX_dev, X_test, y_dev, y_test = train_test_split(\n    X, y, test_size=0.20, stratify=y, random_state=42\n)"),
  md('### 1.5 فصل التدريب والتحقق'),
  code("X_train, X_val, y_train, y_val = train_test_split(\n    X_dev, y_dev, test_size=0.25, stratify=y_dev, random_state=42\n)"),
  md('### 1.6 تحديد أنواع الأعمدة'),
  code("numeric_cols = X.select_dtypes(include='number').columns.tolist()\ncategorical_cols = X.select_dtypes(exclude='number').columns.tolist()"),
  md('### 1.7 تجهيز الأعمدة الرقمية'),
  code("from sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler\n\nnumber_steps = Pipeline([\n    ('impute', SimpleImputer(strategy='median')),\n    ('scale', StandardScaler())\n])"),
  md('### 1.8 تجهيز الأعمدة الفئوية'),
  code("from sklearn.preprocessing import OneHotEncoder\n\ncategory_steps = Pipeline([\n    ('impute', SimpleImputer(strategy='most_frequent')),\n    ('encode', OneHotEncoder(handle_unknown='ignore'))\n])"),
  md('### 1.9 جمع المعالجة'),
  code("from sklearn.compose import ColumnTransformer\n\npreprocess = ColumnTransformer([\n    ('numbers', number_steps, numeric_cols),\n    ('categories', category_steps, categorical_cols)\n])"),
  md('### 1.10 إنشاء Logistic Regression'),
  code("from sklearn.linear_model import LogisticRegression\n\nlogistic = Pipeline([\n    ('preprocess', preprocess),\n    ('model', LogisticRegression(max_iter=1000))\n])"),
  md('### 1.11 تدريب النموذج'), code('logistic.fit(X_train, y_train)'),
  md('### 1.12 استخراج احتمالات التحقق'), code('val_probability = logistic.predict_proba(X_val)[:, 1]'),

  md('# المحطة 2 — أثر العتبة'),
  md('### 2.1 تحويل الاحتمال إلى فئة عند عتبة 0.50'),
  code('prediction_050 = (val_probability >= 0.50).astype(int)'),
  md('### 2.2 حساب مصفوفة الالتباس'),
  code("from sklearn.metrics import confusion_matrix\n\ntn, fp, fn, tp = confusion_matrix(y_val, prediction_050).ravel()\nprint('TP=', tp, 'FP=', fp, 'FN=', fn, 'TN=', tn)"),
  md('### 2.3 حساب Precision وRecall'),
  code("from sklearn.metrics import precision_score, recall_score\n\nprint('Precision:', round(precision_score(y_val, prediction_050), 3))\nprint('Recall:', round(recall_score(y_val, prediction_050), 3))"),
  md('### 2.4 مقارنة ثلاث عتبات\nالحلقة تكرر القياسات نفسها عند ثلاث عتبات فقط.'),
  code("threshold_rows = []\nfor threshold in [0.30, 0.50, 0.70]:\n    prediction = (val_probability >= threshold).astype(int)\n    threshold_rows.append({\n        'العتبة': threshold,\n        'Precision': precision_score(y_val, prediction, zero_division=0),\n        'Recall': recall_score(y_val, prediction, zero_division=0)\n    })"),
  md('### 2.5 عرض المقارنة'), code('display(pd.DataFrame(threshold_rows).round(3))'),

  md('# المحطة 3 — بناء نموذج انحدار'),
  md('### 3.1 تحديد هدف الانحدار'), code("y_reg = df['avg_basket_sar'].copy()"),
  md('### 3.2 إنشاء خصائص الانحدار'),
  code("reg_drop = drop_cols + ['avg_basket_sar']\nX_reg = df.drop(columns=reg_drop, errors='ignore')"),
  md('### 3.3 تقسيم بيانات الانحدار'),
  code("Xr_train, Xr_test, yr_train, yr_test = train_test_split(\n    X_reg, y_reg, test_size=0.20, random_state=42\n)"),
  md('### 3.4 تحديد أنواع أعمدة الانحدار'),
  code("reg_numeric = X_reg.select_dtypes(include='number').columns.tolist()\nreg_categorical = X_reg.select_dtypes(exclude='number').columns.tolist()"),
  md('### 3.5 إنشاء معالجة الانحدار'),
  code("reg_preprocess = ColumnTransformer([\n    ('numbers', number_steps, reg_numeric),\n    ('categories', category_steps, reg_categorical)\n])"),
  md('### 3.6 إنشاء Linear Regression'),
  code("from sklearn.linear_model import LinearRegression\n\nlinear_model = Pipeline([\n    ('preprocess', reg_preprocess),\n    ('model', LinearRegression())\n])"),
  md('### 3.7 تدريب الانحدار'), code('linear_model.fit(Xr_train, yr_train)'),
  md('### 3.8 إنتاج توقعات الانحدار'), code('reg_prediction = linear_model.predict(Xr_test)'),
  md('### 3.9 حساب MAE'),
  code("from sklearn.metrics import mean_absolute_error\n\nmae = mean_absolute_error(yr_test, reg_prediction)\nprint('MAE:', round(mae, 2), 'ريال')"),
  md('### 3.10 حساب RMSE'),
  code("from sklearn.metrics import root_mean_squared_error\n\nrmse = root_mean_squared_error(yr_test, reg_prediction)\nprint('RMSE:', round(rmse, 2), 'ريال')"),
  md('### 3.11 حساب R²'),
  code("from sklearn.metrics import r2_score\n\nr2 = r2_score(yr_test, reg_prediction)\nprint('R²:', round(r2, 3))"),

  md('# المحطة 4 — مقارنة Logistic Regression وRandom Forest'),
  md('### 4.1 حساب PR-AUC للنموذج اللوجستي'),
  code("from sklearn.metrics import average_precision_score\n\nlogistic_pr_auc = average_precision_score(y_val, val_probability)\nprint('Logistic PR-AUC:', round(logistic_pr_auc, 3))"),
  md('### 4.2 إنشاء Random Forest'),
  code("from sklearn.ensemble import RandomForestClassifier\n\nforest = Pipeline([\n    ('preprocess', preprocess),\n    ('model', RandomForestClassifier(\n        n_estimators=100, max_depth=8, min_samples_leaf=5, random_state=42\n    ))\n])"),
  md('### 4.3 تدريب Random Forest'), code('forest.fit(X_train, y_train)'),
  md('### 4.4 استخراج احتمالات Random Forest'), code('forest_probability = forest.predict_proba(X_val)[:, 1]'),
  md('### 4.5 حساب PR-AUC للغابة'),
  code("forest_pr_auc = average_precision_score(y_val, forest_probability)\nprint('Random Forest PR-AUC:', round(forest_pr_auc, 3))"),
  md('### 4.6 عرض مقارنة واضحة'),
  code("comparison = pd.DataFrame({\n    'النموذج': ['Logistic Regression', 'Random Forest'],\n    'Validation PR-AUC': [logistic_pr_auc, forest_pr_auc]\n})\ndisplay(comparison.round(3))"),

  md('# المحطة 5 — فتح الاختبار مرة واحدة'),
  md('### 5.1 اختيار النموذج الأفضل على التحقق'),
  code("chosen_model = forest if forest_pr_auc > logistic_pr_auc else logistic\nchosen_name = 'Random Forest' if forest_pr_auc > logistic_pr_auc else 'Logistic Regression'\nprint('النموذج المختار:', chosen_name)"),
  md('### 5.2 قياسه على الاختبار النهائي'),
  code("test_probability = chosen_model.predict_proba(X_test)[:, 1]\ntest_pr_auc = average_precision_score(y_test, test_probability)\nprint('Final Test PR-AUC:', round(test_pr_auc, 3))"),
  md('## الخلاصة\nفصلنا كل قرار: البيانات، التقسيم، المعالجة، التدريب، الاحتمال، العتبة، المقاييس، ثم المقارنة والاختبار النهائي.')
]);

console.log('Beginner labs rebuilt.');
